# Generated by Django 2.2 on 2020-06-13 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('points', models.PositiveIntegerField(default=0)),
                ('team', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.PROTECT, related_name='point_team', to='cricket.Team')),
            ],
            options={
                'verbose_name': 'MatchPoints',
                'ordering': ['-points'],
            },
        ),
    ]
