# Generated by Django 2.2 on 2020-06-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_matchpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(max_length=4096, upload_to='cricket_images', verbose_name='Team Logo'),
        ),
    ]
