# Generated by Django 2.2 on 2020-06-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_auto_20200613_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, max_length=4096, null=True, upload_to='cricket_images/', verbose_name='Player Image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(max_length=4096, upload_to='cricket_images/', verbose_name='Team Logo'),
        ),
    ]
